theme: jekyll-theme-slate
title: Chaos Hearing
description: At the intersection of sound physics, auditory cognition, and interface design.
baseurl: /chaoshearing
url: https://intelligent-interfaces.github.io

# Serve from repo root (not /docs)
include:
  - projects
  - sources

exclude:
  - requirements.txt
  - "*.pdf"
  - LICENSE
